[package]
name = "mh-mod-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
#compress-tools = "0.14.3"
gtk4 = { version = "0.8.1", features = ["v4_10", "v4_12"] }
relm4 = "0.8.1"
relm4-components = "0.8.1"
